version: '3.8'

services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: EXP3_S8
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=ga30df92c84b97d_fullstack_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
      SPRING_DATASOURCE_USERNAME: ADMIN
      SPRING_DATASOURCE_PASSWORD: Secure1Password2Example
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.OracleDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_ORG_HIBERNATE: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
    restart: always
